name = "BoGGoGNewton"
uuid = "dae22de2-c073-4670-873b-c26cef6bfee0"
authors = ["Julian Stobbe <Atomtomate@gmx.de>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
